### ISSUE TITLE
Can we change Localization for Review Dialog ?

### ISSUE THREAD

**Issue by Ghousepasha-ios** [CleverTap/ios-request-review#1]
Is it possible to localize the text showing for review dialog box. For example Enjoying app_name?, Tap a star to rate, Cancel, Submit and Not now button texts from infoPlist localization file?

**Comment by pwilkniss** [comment]
@ghouse1 don't think so.  Seems display including localization is internal to SKStoreReviewController.

**Comment by Ghousepasha-ios** [comment]
@pwilkniss ,
Thanks, I thought the same. It's not possible for now.
